name: Setup
runs:
  using: "composite"
  steps:
    - name: Cache aqua tools
      uses: actions/cache@v4
      with:
        path: ~/.local/share/aquaproj-aqua
        key: ${{ runner.os }}-aqua-${{ hashFiles('aqua.yaml') }}
        restore-keys: |
          ${{ runner.os }}-aqua-

    - name: Install aqua
      uses: aquaproj/aqua-installer@v2.3.0
      with:
        aqua_version: v2.23.0
        aqua_opts: ""

    - name: Config Terraform plugin cache
      run: |
        echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' >~/.terraformrc
        mkdir --parents ~/.terraform.d/plugin-cache
      shell: bash

    - name: Cache Terraform Plugins
      uses: actions/cache@v4
      with:
        path: ~/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          ${{ runner.os }}-terraform-
