name: Terraform PR check

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, ready_for_review]
    branches:
      - main

env:
  TERRAGRUNT_TFPATH: terraform

permissions:
  contents: write
  pull-requests: write

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub App token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout assets
        uses: actions/checkout@v4
        with:
          repository: takapg/terraform-cicd-test-assets
          ref: main
          path: ./assets/
          token: ${{ steps.app-token.outputs.token }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Download terraform assets
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          # git clone --depth 1 https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/takapg/terraform-cicd-test-assets.git /tmp/terraform-cicd-test-assets/
          ls -la ./assets/

      - name: Setup
        uses: ./.github/actions/setup

      - name: Init
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            cd files/terraform
            tfenv use min-required

            cd ${{ github.workspace }}/accounts
            terragrunt run-all init -upgrade

      - name: Run scripts
        run: |
          chmod +x scripts/*
          ./scripts/generate_terraform_version_files.sh
          ./scripts/add_required_providers_to_version_file.sh
          ./scripts/update_dependency_lock_files.sh

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

      - name: Auto commit
        id: auto-commit
        if: always()
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          committer_name: "github-actions[bot]"
          committer_email: "github-actions[bot]@users.noreply.github.com"
          message: "chore: ${{ github.workflow }} (${{ github.job }})"

      - name: Cancel workflow
        run: |
          if [ "${{ steps.auto-commit.outputs.committed }}" == "true" ]; then
            exit 1
          fi

  plan:
    needs: [check-code]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Plan and comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd accounts
          $(git rev-parse --show-toplevel)/scripts/output_plan_results.sh
          github-comment exec -k default -- cat plan_results.md
          github-comment hide
