name: Terraform PR check

on:
  workflow_dispatch:
  # pull_request:
  #   types: [synchronize, opened, ready_for_review]
  #   branches:
  #     - main

env:
  TERRAGRUNT_TFPATH: terraform

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.16.4

      - name: Plan
        run: |
          cd accounts
          terragrunt run-all plan --terragrunt-log-level debug

      - name: Test
        run: |
          echo 'test'
          terragrunt --version
