name: Terraform PR check

on:
  workflow_dispatch:
  # pull_request:
  #   types: [synchronize, opened, ready_for_review]
  #   branches:
  #     - main

env:
  TERRAGRUNT_TFPATH: terraform
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.16.4

      - name: Create Terraform plugin cache dir
        run: |
          mkdir -p $TF_PLUGIN_CACHE_DIR

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

      - name: Auto commit
        if: always()
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          committer_name: "github-actions[bot]"
          committer_email: "github-actions[bot]@users.noreply.github.com"
          message: "chore: pre-commit"

  plan:
    needs: [pre-commit]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.16.4

      - name: Create Terraform plugin cache dir
        run: |
          mkdir -p $TF_PLUGIN_CACHE_DIR

      - name: Plan
        run: |
          cd accounts
          terragrunt run-all init --terragrunt-parallelism 1
          terragrunt run-all plan

      - name: Test
        run: |
          echo 'test'
