name: Terraform apply

on:
  pull_request:
    branches:
      - main
    types: [closed]

env:
  TERRAGRUNT_TFPATH: terraform
  TENV_QUIET: t
  TENV_AUTO_INSTALL: true

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub App token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ steps.app-token.outputs.token }}

      - name: Download terraform assets
        uses: ./.github/actions/download-terraform-assets
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup
        uses: ./.github/actions/setup

      - name: Init
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            cd accounts
            terragrunt run-all init

      - name: Apply
        run: |
          cd accounts
          terragrunt run-all apply --terragrunt-non-interactive

      - name: Upload terraform assets
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          find . -not -path '*/.terraform/*' -name 'terraform.tfstate' \
            | xargs -I{} bash -c 'tfstate_path=/tmp/terraform-cicd-test-assets/tfstate/{} && mkdir -p $(dirname ${tfstate_path}) && cp {} ${tfstate_path}'
          cd /tmp/terraform-cicd-test-assets/
          (git add . && git diff --staged --exit-code) \
            || (git -c user.name='github-actions[bot]' -c user.email='github-actions[bot]@users.noreply.github.com' commit -m 'update' && git push origin main)
