name: Terraform PR check

on:
  workflow_dispatch:
  # pull_request:
  #   types: [synchronize, opened, ready_for_review]
  #   branches:
  #     - main

env:
  TERRAGRUNT_TFPATH: terraform

permissions:
  contents: write
  pull-requests: write

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Init
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            cd files/terraform
            tfenv use min-required

            cd ${{ github.workspace }}/accounts
            terragrunt run-all init

      - name: Generate .terraform-version
        run: |
          find accounts -name version.tf |
          xargs -I{} hcledit --file {} attribute get terraform.required_version |
          tr -d '"'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

      - name: Auto commit
        if: always()
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          committer_name: "github-actions[bot]"
          committer_email: "github-actions[bot]@users.noreply.github.com"
          message: "chore: ${{ github.workflow }} (${{ github.job }})"

  plan:
    needs: [check-code]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Plan
        run: |
          cd accounts
          terragrunt run-all plan

      - name: Test
        run: |
          echo 'test'
